apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-web
spec:
  replicas: 4
  revisionHistoryLimit: 5
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      #maxUnavailable: 20%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: node-web
        env: staging
    spec:
      containers:
      - name: node-web
        image: richarvey/nginx-php-fpm
        #image: tutum/apache-php
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # health checks self healing check port 80 response 200, if containers error (400-500) kubernetes restart the pod
        livenessProbe:
           httpGet:
             path: /
             port: 80
           # length of time to wait for a pod to initialize
           # after pod startup, before applying health checking
           initialDelaySeconds: 30
           timeoutSeconds: 2
        resources:
           requests:
              cpu: "80m"
              memory: "128Mi"
           limits:
              cpu: "1000m"
              memory: "1024Mi"
