apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-web
spec:
  replicas: 5
  revisionHistoryLimit: 5
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: node-web
        env: staging
    spec:
      containers:
      - name: node-web
        image: smebberson/alpine-nginx
        #image: richarvey/nginx-php-fpm
        #image: tutum/apache-php
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
            requests:
               cpu: "80m"
               memory: "40Mi"
            limits:
               cpu: "900m"
               memory: "1024Mi"
        # health checks self healing check port 80 response 200,
        # if containers error (400-500) kubernetes restart the pod
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 5
        livenessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 25
           periodSeconds: 5
