apiVersion: v1
kind: Service
metadata:
  name: node-web
  labels:
    app: node-web
spec:
  selector:
    app: node-web
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30032
  type: LoadBalancer
